ShakeHands/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('questionBoxes/', include('questionBoxes.urls', namespace = 'questionBoxes')),
    path('address_exchange/', include('addexchange.urls', namespace = 'addexchange')),
    path('',include('mypage.urls', namespace ='mypage')),
]

# 以下、media用の定義
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    #path('', views.Top.as_view(), name='login'),
    path('', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('signup/', views.UserCreate.as_view(),name='signup'),
    path('signup/done/', views.UserCreateDone.as_view(),name='signup_done'),
    path('signup/setting/<token>/', views.UserCreatesetting.as_view(),name='signup_setting'),
    path('signup/complete/', views.UserCreateComplete.as_view(),name='signup_complete'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('setting/',views.UserSettingUpdate.as_view(),name='accountsSetting'),
    path('setting/icon',views.iconPic_change.as_view(),name='iconSetting'),
    path('setting/topmessage',views.commentChange.as_view(), name='commentChange'),
]

addexchange/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name ='addexchange'
urlpatterns=[
    path('request/<uuid:id>/',views.addExc.as_view(),name='request'),
    path('list/',views.addExchange_list.as_view(),name='list'),
    path('detail/<uuid:id>/',views.detail.as_view(),name='detail'),
    path('approve/<uuid:id>/',views.confirm.as_view(),name='confirm'),
]

mypage/urls.py
from . import views
from django.urls import path, include
#from django.contrib.auth import views as auth_views

app_name = 'mypage'

urlpatterns = [
    path('', views.top.as_view(), name='top'),

    #学生生活情報の編集ページ
    path('setting/univlife/',views.settingUnivLifeInfo.as_view(), name='univlife_setting'),
    path('setting/univlife/club/add/',views.addClub.as_view(), name='univlife_club_add'),
    path('setting/univlife/club/update/<int:id>',views.updateClub.as_view(), name='univlife_club_update'),
    path('setting/univlife/club/delete/<int:id>',views.deleteClub.as_view(), name='univlife_club_delete'),
    path('setting/univlife/openQ/add/',views.addopenQ.as_view(), name='univlife_openQ_add'),
    path('setting/univlife/openQ/update/<int:id>',views.updateOpenQ.as_view(), name='univlife_openQ_update'),
    path('setting/univlife/openQ/delete/<int:id>',views.deleteOpenQ.as_view(), name='univlife_openQ_delete'),

    #就活情報の編集ページ
    path('setting/jobhunting/',views.setting_jobHuntingInfo.as_view(), name='jobhunting_setting'),
    path('setting/jobhunting/policy',views.jobHuntingPolicy_view.as_view(), name='jobhunting_policy'),
    path('setting/jobhunting/startTime',views.jobHunting_startTime_view.as_view(), name='jobhunting_startTime'),
    path('setting/jobhunting/requestment',views.jobHunting_requestment_view.as_view(), name='jobhunting_requestment'),
    path('setting/jobhunting/internship/create',views.internshipRec_create.as_view(), name='jobhunting_internRec_create'),
    path('setting/jobhunting/internship/update/<uuid:id>',views.internshipRec_update.as_view(), name='jobhunting_internRec_update'),
    path('setting/jobhunting/internship/delete/<uuid:id>',views.internshipRec_delete.as_view(), name='jobhunting_internRec_delete'),
    path('setting/jobhunting/prospectiveEmployer/create',views.prospectiveEmployer_create.as_view(), name='jobhunting_prospectiveEmployer_create'),
    path('setting/jobhunting/prospectiveEmployer/update/<uuid:id>',views.prospectiveEmployer_update.as_view(), name='jobhunting_prospectiveEmployer_update'),
    path('setting/jobhunting/prospectiveEmployer/delete/<uuid:id>',views.prospectiveEmployer_delete.as_view(), name='jobhunting_prospectiveEmployer_delete'),

    #プロフィールページ
    path('profile/<uuid:id>',views.profilePage.as_view(),name='profile'),
    path('search/all',views.allUser_list.as_view(),name='alluser_list'),

    #フォロー一覧
    path('friends/', views.follower_list.as_view(), name='follower_list'),
    path('search/',views.Search.as_view(),name='searchuser'),
]

questionBoxes/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'questionBoxes'

urlpatterns = [
    #path('', views.Top.as_view(), name='login'),
    path('create/<uuid:id>', views.CreateQuestionView.as_view(), name='create'),
    path('answer/<uuid:id>', views.AnswerView.as_view(), name='answer'),
    path('list/',views.list.as_view(),name='list'),
    path('detail/<uuid:id>', views.QBoxView.as_view(),name='detail'),
    path('search_questionbox/',views.Search_question.as_view(),name='searchquestion')
]

accounts/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.base_user import BaseUserManager
from django.core.validators import MaxValueValidator, MinValueValidator

import uuid
from json import JSONEncoder
from uuid import UUID

JSONEncoder_olddefault = JSONEncoder.default

def JSONEncoder_newdefault(self, o):
    if isinstance(o, UUID): return str(o)
    return JSONEncoder_olddefault(self, o)

JSONEncoder.default = JSONEncoder_newdefault


class UserManager(BaseUserManager):
    """ユーザーマネージャー."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """メールアドレスでの登録を必須にする"""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """is_staff(管理サイトにログインできるか)と、is_superuer(全ての権限)をFalseに"""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """スーパーユーザーは、is_staffとis_superuserをTrueに"""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """カスタムユーザーモデル."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=False)
    last_name = models.CharField(_('last name'), max_length=150, blank=False)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """Return the first_name plus the last_name, with a space in
        between."""
        full_name = '%s %s' % (self.last_name, self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)


    @property
    def username(self):
        """username属性のゲッター

        他アプリケーションが、username属性にアクセスした場合に備えて定義
        メールアドレスを返す
        """
        return self.email



COURSE_CHOICES=(
    ('1','英語英文学科'),
    ('2','国際関係学科'),
    ('3','多文化・国際協力学科'),
    ('4','数学科'),
    ('5','情報科学科'),
    ('6','総合政策学科'),
)
class UserSetting(models.Model):
    #仮登録だったユーザを本登録するためのModel
    #姓名とemailはCreateUserの方で登録してある。
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    display_name = models.CharField("表示名",max_length=50,blank=True)
    icon_pic = models.ImageField( "アイコン画像" , upload_to='images/', blank=True, null=True)
    graduation_year = models.IntegerField("卒業年(西暦下2桁)",blank=False,validators=[MinValueValidator(0),MaxValueValidator(99)])
    course = models.CharField("所属学科",max_length=2,choices=COURSE_CHOICES,blank=False)

class userComment(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    comment = models.TextField("自己紹介", max_length=200, null=True)

accounts/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.forms import (
    UserCreationForm, AuthenticationForm, PasswordChangeForm,
    PasswordResetForm, SetPasswordForm
)
from django.contrib.auth import get_user_model
from .models import (
    UserSetting,userComment
)
from PIL import Image
from django.core.files import File


User = get_user_model()


class LoginForm(AuthenticationForm):
    """ログインフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label  # placeholderにフィールドのラベルを入れる



class UserCreateForm(UserCreationForm):
    """ユーザー登録用フォーム"""

    class Meta:
        model = User
        fields = ('email','last_name','first_name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    def clean_email(self):#clean_[フィールド名]のメゾットを定義するとそこで入力検証が行われる
        #もし重複するアクティブでない(仮登録だけして本登録をしないまま、登録フォームが期限切れしたなどした残骸を削除する)
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        if not(email.endswith('@gm.tsuda.ac.jp')):
            raise forms.ValidationError("@tsuda.ac.jpのメールアドレスを指定してください。")
        return email




COURSE_CHOICES=(
    ('1','英語英文学科'),
    ('2','国際関係学科'),
    ('3','多文化・国際協力学科'),
    ('4','数学科'),
    ('5','情報科学科'),
    ('6','総合政策学科'),
)
class UserSettingForm(forms.ModelForm):
    #メールアドレス認証後の設定form
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['display_name'].required = False
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
    class Meta:
        model = UserSetting
        fields = (
            'graduation_year',
            'course',
            'display_name',
        )
    def clean_graduation_year(self):
        graduation_year = self.cleaned_data['graduation_year']
        if(int(graduation_year)>=100):
            raise forms.ValidationError('卒業年度は西暦の下二桁を入力してください。')
        return graduation_year

    




class MyPasswordResetForm(PasswordResetForm):
    """パスワード忘れたときのフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MySetPasswordForm(SetPasswordForm):
    """パスワード再設定用フォーム(パスワード忘れて再設定)"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class iconChangeForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = UserSetting
        fields = ('icon_pic','x','y','width','height',)

    def save(self):
        icon = super(iconChangeForm,self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')
        r = w if (w<=h) else h

        image = Image.open(icon.icon_pic)
        RectImage = image.crop((x,y,(r+x),(r+y)))
        resizedImage = RectImage.resize((300,300),Image.ANTIALIAS)
        resizedImage.save(icon.icon_pic.path)

        return icon

class comment_form(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(comment_form, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
    class Meta:
        model = userComment
        fields = (
            'comment',
        )

accounts/templates/accounts/base.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/drawer.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    {% block class %}{% endblock %}

    <script src="https://kit.fontawesome.com/d3c761ab9c.js" crossorigin="anonymous"></script>
    
    <link rel="icon" href="{% static 'img/noicons.jpg' %}">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
   

    <title>ShakeHands</title>
</head>
<body class="drawer drawer--left drawer--sidebar">
    <header role="banner">
        <button type="button" class="drawer-toggle drawer-hamburger">
          <span class="sr-only">toggle navigation</span>
          <span class="drawer-hamburger-icon"></span>
        </button>

        <nav class="drawer-nav mydrawer_setting" role="navigation">
          <ul class="drawer-menu">
            <div class="drawer_top">
                <h3><a href="{% url 'mypage:top' %}" style="text-decoration: none; color: #d0eae8;">ShakeHands</a></h3>
            </div>
              {% if user.is_authenticated %}
                            
              <div class="card">
                <div class="mycard-header " role="tab" id="collapseListGroupHeading1">
                  <a href="#collapseListGroup1" class="collapsed text-body dropdown-toggle" role="button" data-toggle="collapse" aria-expanded="false" aria-controls="collapseListGroup1" style="display: block;">ユーザ設定</a>
                </div><!-- /.card-header -->  
                <div class="collapse" role="tabpanel" id="collapseListGroup1" aria-labelledby="collapseListGroupHeading1" aria-expanded="false">
                    <ul class="list-group list-group-flush">
                        <li><a class="drawer-dropdown-menu-item" href="{% url 'accounts:iconSetting' %}">アイコン画像を変更</a></li>
                        <li><a class="drawer-dropdown-menu-item" href="{% url 'accounts:commentChange' %}">トップコメントを変更</a></li>
                        <li><a class="drawer-dropdown-menu-item" href="{% url 'accounts:accountsSetting' %}">アカウント情報を更新</a></li>
                    </ul>
                </div>                
              </div>

              <div class="card">
                  <div class="mycard-header " role="tab" id="collapseListGroupHeading1">
                    <a href="#collapseListGroup2" class="collapsed text-body dropdown-toggle" role="button" data-toggle="collapse" aria-expanded="false" aria-controls="collapseListGroup2" style="display: block">プロフィールを更新</a>
                  </div><!-- /.card-header -->  
                  <div class="collapse" role="tabpanel" id="collapseListGroup2" aria-labelledby="collapseListGroupHeading2" aria-expanded="false">
                      <ul class="list-group list-group-flush">
                        <li><a class="drawer-dropdown-menu-item" href="{% url 'mypage:univlife_setting' %}">学生生活情報を更新</a></li>
                        <li><a class="drawer-dropdown-menu-item" href="{% url 'mypage:jobhunting_setting' %}">就活情報を更新</a></li>
                        <li><a class="drawer-dropdown-menu-item" href="{% url 'mypage:profile' id=user.pk %}">プロフィールを確認</a></li>
                      </ul>
                  </div>                
                </div>
                <div class="card">
                  <div class="mycard-header " role="tab" id="collapseListGroupHeading1">
                    <a href="#collapseListGroup3" class="collapsed text-body dropdown-toggle" role="button" data-toggle="collapse" aria-expanded="false" aria-controls="collapseListGroup3" style="display: block">検索</a>
                  </div><!-- /.card-header -->  
                  <div class="collapse" role="tabpanel" id="collapseListGroup3" aria-labelledby="collapseListGroupHeading3" aria-expanded="false">
                      <ul class="list-group list-group-flush">
                        <li><a class="drawer-dropdown-menu-item" href="{% url 'mypage:searchuser' %}">ユーザー検索</a></li>
                        <li><a class="drawer-dropdown-menu-item" href="{% url 'questionBoxes:searchquestion' %}">質問検索</a></li>
                        
                      </ul>
                  </div>                
                </div>
              <li><a class="drawer-dropdown-menu-item" href="{% url 'addexchange:list' %}">アドレス交換申請一覧</a></li>
              <li><a class="drawer-dropdown-menu-item" href="{% url 'questionBoxes:list' %}">質問箱一覧</a></li>
              <li><a class="drawer-dropdown-menu-item" href="{% url 'mypage:follower_list' %}">フォロー一覧</a></li>
              <div class="dropdown-divider"></div>
              <li><a class="drawer-dropdown-menu-item" href="{% url 'accounts:logout' %}">ログアウト</a></li>
              
              {% else %}
              <li class="nav-item">
                <a class="drawer-dropdown-menu-item" href="{% url 'accounts:login' %}">
                ログイン
              </a>
              </li>
              {% endif %}
              
              
          </ul>
          
        </nav>
        <div class="container-fluid">
          <div class="row" style="border-bottom:solid 0.1px #e2e2e2;">
            <div class="col align-self-center">
              <a href="{% url 'mypage:top' %}">
                <img src="{% static 'img/logo_long.svg' %}" height="40px" style="margin-top: 8px;margin-bottom: 8px; " class="col align-self-center">
              </a>            
            </div>
          </div>
        </div>

      </header>
      <main role="main" class="drawer-contents">
          <section class="item bg-amber">
          <div class="nav-margin" style="margin-top: 40px;">
            {% block content %}{% endblock %}
          </div>     
        <!-- Page content -->
        </section>
      </main>
      

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/iscroll.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/drawer.min.js' %}" charset="utf-8"></script>
    {% block jsclass %}{% endblock %}
    <script>
        $(document).ready(function() {
          $('.drawer').drawer();
        });
    </script>
</body>
</html>

accounts/templates/accounts/login.html
{% extends "accounts/base.html" %}
{% load static %}
{% block class %}
<!-- cssを追加できる -->
<link href="{% static 'css/login.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="row">
    <!-- 左側、ログインエリア -->

        <div class="card col-md-6 login_form">
            <h3>login</h3>
            <div class="card-body">
                <form action="{% url 'accounts:login' %}" method="POST">
                {% csrf_token %}
                    {{ form.non_field_errors }}
                    {% for field in form %}
                        {{ field }}
                        {{ field.errors }}
                        <hr>
                    {% endfor %}
                    <button type="submit" class="btn btn-outline-info btn-lg" >ログイン</button>
                    <input type="hidden" name="next" value="{{ next }}" />
                </form>
            </div>
        </div>

    <!-- 左側、ログインエリアおわり -->

    <!-- 右側、会員登録エリア -->
    <div class="card col-md-6 container">
        <div class="card-body row" col align-self-center>
            <div style="margin-bottom: 10px;" class="col-8 offset-2">
                <a href="{% url 'accounts:signup' %}" style="display:inline">新規会員登録</a>
            </div>
            <div class="col-6 offset-2">
                <a href="{% url 'accounts:password_reset' %}">パスワード再設定</a>    
            </div>  
        </div>
    </div><!-- 右側、会員登録エリアおわり -->
</div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends "accounts/base.html" %}
{% block content %}
<p>ログアウトしました</p>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends "accounts/base.html" %}
{% block content %}
<p>
    パスワード再設定を完了しました。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'accounts:login' %}">ログイン</a>
</p>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "accounts/base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-outline-info btn-lg">送信</button>
</form>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends "accounts/base.html" %}
{% block content %}
<p>
    パスワード再設定用のメールを送信しました。<br>
    メールに記載されているリンクから再設定を行ってください。
</p>
{% endblock %}

accounts/templates/accounts/password_reset_form.html
{% extends "accounts/base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-outline-info btn-lg">送信</button>
</form>
{% endblock %}

accounts/templates/accounts/set_iconpic.html
{% extends "accounts/base.html" %}
{% load static %}
{% block class %}
<!-- cssを追加できる -->
<link href="{% static 'css/cropper.min.css' %}" rel="stylesheet">
{% endblock %}

{% block jsclass %}
<!-- jsを追加できる -->
<script src="{% static 'js/cropper.min.js' %}"></script>
<script>
    $(function () {
        /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
        /* Displaying the preview inside a modal after the user selects the image */       
        $("#id_icon_pic").change(function () {
            if (this.files && this.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("#image").attr("src", e.target.result);
                    $("#modalCrop").modal("show");
                }
                reader.readAsDataURL(this.files[0]);
            }
          });
    
        /* SCRIPTS TO HANDLE THE CROPPER BOX */
        var $image = $("#image");          
        var cropBoxData;
        var canvasData;
        var cropper;
        
        $("#modalCrop").on("shown.bs.modal", function () {
            cropper = new Cropper(image,{
                viewMode: 1,
                aspectRatio: 1/1,
                minCropBoxWidth: 200,
                minCropBoxHeight: 200,
                responsive:true,
                restore:true,
                ready: function () {
                //should set crop box data first here
                cropper.setCropBoxData(cropBoxData).setCanvasData(canvasData);
                }
            });
        }).on("hidden.bs.modal", function () {
            cropBoxData = cropper.getCropBoxData();
            canvasData = cropper.getCanvasData();
            cropper.destroy();
        });
    
        /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
        $(".js-crop-and-upload").click(function () {
            var cropData = cropper.getData();/* ここ変えた */
            console.log(cropData)
            $("#id_x").val(cropData["x"]);
            $("#id_y").val(cropData["y"]);
            $("#id_height").val(cropData["height"]);
            $("#id_width").val(cropData["width"]);
            $("#formUpload").submit();
        });   
    });
</script>
{% endblock %}

{% block content %}
<form action="" method="POST" enctype="multipart/form-data" id="formUpload">
  {% csrf_token %}
  {{ form.non_field_errors }}

  <div class="form-group">
      <label for="{{ form.icon_pic.id_for_label }}">{{form.icon_pic.label_tag}}</label><br>
      <img src="{{icon_now.url}}" width="200"/>
      {{form.icon_pic}}
      <input type="hidden" name="x" value="" id="id_x">
      <input type="hidden" name="y" value="" id="id_y">
      <input type="hidden" name="width" value="" id="id_width">
      <input type="hidden" name="height" value="" id="id_height">
  </div>          
</form>

<!-- MODAL TO CROP THE IMAGE -->
<div class="modal fade" id="modalCrop">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Crop the photo</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
              <div class="media">
                <img src="" id="image" style="max-width: 100%;">
              </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
                <button type="button" class="btn btn-outline-info js-crop-and-upload">Crop and upload</button>
            </div>
        </div>
    </div>  
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "accounts/base.html" %}
{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}

    <button type="submit" class="btn btn-outline-info btn-lg">送信</button>
</form>
{% endblock %}

accounts/templates/accounts/signup_complete.html
{% extends "accounts/base.html" %}
{% block content %}
<p>
    会員登録が完了しました。
</p>
{% endblock %}

accounts/templates/accounts/signup_done.html
{% extends "accounts/base.html" %}
{% block content %}
<p>
    会員登録確認メールを送信しました。まだ、会員登録は完了していません。<br>
    確認メールを送信しましたので、確認メールに記載されているリンクから本登録を行ってください。
</p>
{% endblock %}

accounts/templates/accounts/signup_setting.html
{% extends "accounts/base.html" %}
{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}

    <button type="submit" class="btn btn-outline-info btn-lg">送信</button>
</form>
{% endblock %}