ShakeHands/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('questionBoxes/', include('questionBoxes.urls', namespace = 'questionBoxes')),
    path('address_exchange/', include('addexchange.urls', namespace = 'addexchange')),
    path('',include('mypage.urls', namespace ='mypage')),
]

# 以下、media用の定義
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mypage/urls.py
from . import views
from django.urls import path, include
#from django.contrib.auth import views as auth_views

app_name = 'mypage'

urlpatterns = [
    path('', views.top.as_view(), name='top'),

    #学生生活情報の編集ページ
    path('setting/univlife/',views.settingUnivLifeInfo.as_view(), name='univlife_setting'),
    path('setting/univlife/club/add/',views.addClub.as_view(), name='univlife_club_add'),
    path('setting/univlife/club/update/<int:id>',views.updateClub.as_view(), name='univlife_club_update'),
    path('setting/univlife/club/delete/<int:id>',views.deleteClub.as_view(), name='univlife_club_delete'),
    path('setting/univlife/openQ/add/',views.addopenQ.as_view(), name='univlife_openQ_add'),
    path('setting/univlife/openQ/update/<int:id>',views.updateOpenQ.as_view(), name='univlife_openQ_update'),
    path('setting/univlife/openQ/delete/<int:id>',views.deleteOpenQ.as_view(), name='univlife_openQ_delete'),

    #就活情報の編集ページ
    path('setting/jobhunting/',views.setting_jobHuntingInfo.as_view(), name='jobhunting_setting'),
    path('setting/jobhunting/policy',views.jobHuntingPolicy_view.as_view(), name='jobhunting_policy'),
    path('setting/jobhunting/startTime',views.jobHunting_startTime_view.as_view(), name='jobhunting_startTime'),
    path('setting/jobhunting/requestment',views.jobHunting_requestment_view.as_view(), name='jobhunting_requestment'),
    path('setting/jobhunting/internship/create',views.internshipRec_create.as_view(), name='jobhunting_internRec_create'),
    path('setting/jobhunting/internship/update/<uuid:id>',views.internshipRec_update.as_view(), name='jobhunting_internRec_update'),
    path('setting/jobhunting/internship/delete/<uuid:id>',views.internshipRec_delete.as_view(), name='jobhunting_internRec_delete'),
    path('setting/jobhunting/prospectiveEmployer/create',views.prospectiveEmployer_create.as_view(), name='jobhunting_prospectiveEmployer_create'),
    path('setting/jobhunting/prospectiveEmployer/update/<uuid:id>',views.prospectiveEmployer_update.as_view(), name='jobhunting_prospectiveEmployer_update'),
    path('setting/jobhunting/prospectiveEmployer/delete/<uuid:id>',views.prospectiveEmployer_delete.as_view(), name='jobhunting_prospectiveEmployer_delete'),

    #プロフィールページ
    path('profile/<uuid:id>',views.profilePage.as_view(),name='profile'),
    path('search/all',views.allUser_list.as_view(),name='alluser_list'),

    #フォロー一覧
    path('friends/', views.follower_list.as_view(), name='follower_list'),
    path('search/',views.Search.as_view(),name='searchuser'),
]

mypage/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils import timezone
from accounts.models import(
    User
)

"""以下UUIDを利用するための設定"""
import uuid
from json import JSONEncoder
from uuid import UUID
JSONEncoder_olddefault = JSONEncoder.default
def JSONEncoder_newdefault(self, o):
    if isinstance(o, UUID): return str(o)
    return JSONEncoder_olddefault(self, o)
JSONEncoder.default = JSONEncoder_newdefault



# Create your models here.
"""
＿＿＿＿＿＿＿＿就活関連のモデル＿＿＿＿＿＿＿＿＿
＊業界モデル
＊職種モデル
＊就活希望条件モデル
＊就活開始時期モデル
＊おすすめのインターンシップモデル
＊内定済の会社モデル
"""
class industry(models.Model):
    #業界[id,大分類,小分類]　
    auto_increment_id = models.AutoField(primary_key=True)
    industry_classification = models.CharField("業界分類",max_length=50)
    industry = models.CharField("業界",max_length=50,blank=True)
    def __str__(self):
        if(len(self.industry)==0):
            return str(self.industry_classification+" 業界")
        return str(self.industry_classification+" "+self.industry+" 業界")

class occupation(models.Model):
    #職種[id,職種]　
    auto_increment_id = models.AutoField(primary_key=True)
    occupation = models.CharField("職種", max_length=50)
    def __str__(self):
        return self.occupation

class jobHunting_requestment(models.Model):
    #就職希望[業界、職種、勤務地]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    industry = models.ForeignKey(industry, verbose_name='希望業界', on_delete=models.CASCADE)
    occupation = models.ForeignKey(occupation, verbose_name='希望職種', on_delete=models.CASCADE)
    workplace = models.CharField("希望勤務地", max_length=255, blank=True, null=True)

class jobHunting_startTime(models.Model):
    #就活を始めた時期[時期]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    season = models.CharField("時期", max_length=50, blank=False, null=True)
    def __str__(self):
        return self.season

class internshipRecommendation(models.Model):
    #インターン情報[業界、職種、社名、時期、期間、内容、感想、最終更新日、1対多の関係]
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    industry = models.ForeignKey(industry, verbose_name='業界', on_delete=models.CASCADE, blank=True, null=True)
    occupation = models.ForeignKey(occupation, verbose_name='職種', on_delete=models.CASCADE, blank=True, null=True)
    company_name = models.CharField("社名", max_length=50)
    season = models.CharField("時期", max_length=50)
    period = models.CharField("期間", max_length=50)
    overView = models.TextField("内容", max_length=500)
    implessions = models.TextField("感想", max_length=300,blank=True, null=True)
    post_date = models.DateTimeField("最終更新日", auto_now= True)

class prospectiveEmployer(models.Model):
    #内定済みの会社[業界、職種、社名、1対多の関係]
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    industry = models.ForeignKey(industry, verbose_name='業界', on_delete=models.CASCADE)
    occupation = models.ForeignKey(occupation, verbose_name='職種', on_delete=models.CASCADE)
    company_name = models.CharField("社名", max_length=50)

class jobHunting_policy(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    policy = models.TextField("就活の軸", max_length=300, blank=False, null=True)
    def __str__(self):
        return self.policy






"""
______________友達＿＿＿＿＿＿＿＿＿＿＿
＊友達モデル
"""
class myfriend(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE, related_name='user')
    friend = models.ForeignKey(User, on_delete = models.CASCADE, related_name='friend')







"""
_______________学生生活＿＿＿＿＿＿＿＿＿＿＿
＊所属団体モデル
＊OpenQuestionモデル
＊OpenQuestion回答モデル
"""
class club(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    club_name = models.CharField("団体名", max_length=60,blank=True)
    post_date = models.DateTimeField("最終更新日", auto_now= True)

class openQ(models.Model):
    q_text = models.TextField("Q")
    def __str__(self):
        return self.q_text

class openQ_ans(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    openQ = models.ForeignKey(openQ, on_delete=models.PROTECT)
    ans = models.TextField("回答",max_length=1000)
    post_date = models.DateTimeField("最終更新日", auto_now= True)
    def __str__(self):
        return self.ans

mypage/views.py
from django.shortcuts import redirect,render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.forms import modelformset_factory
from .forms import(
    club_form, openQ_ans_addform, openQ_ans_updateform,
    jobHunting_startTime_form, jobHunting_requestment_form,
    internshipRec_form, prospectiveEmployer_form,
    myfriend_form, jobHunting_policy_form
)
from .models import(
    club, openQ_ans, openQ_ans,
    industry, occupation, prospectiveEmployer,
    jobHunting_startTime, jobHunting_requestment,
    internshipRecommendation,
    myfriend,jobHunting_policy
)
from questionBoxes.models import Question
from addexchange.models import addressExchange
from accounts.models import(UserSetting,userComment)
import datetime
from dateutil.relativedelta import relativedelta
User = get_user_model()

# Create your views here.
"""
新規フォロワーを一覧表示する
届いた質問箱の未回答のものを一覧表示する
届いたアドレス交換申請の未返答のものを一覧表示する
"""
class top(LoginRequiredMixin,generic.TemplateView):
    template_name = 'mypage/top.html'
    def get_context_data(self, **kwargs):
        login_user = self.request.user
        today=datetime.date.today()+relativedelta(days=1)
        threemonths_ago=today-relativedelta(months=3)
        context = super().get_context_data(**kwargs)
        followed = myfriend.objects.values('user').filter(friend=login_user).order_by('id')
        I_unanswered_qBox = Question.objects.filter(answerer=login_user, status=1).filter(created_at__range=(threemonths_ago,today)).order_by('created_at')
        I_unanswered_addExc = addressExchange.objects.filter(answerer=login_user).filter(approve_boolean=None).filter(request_time__range=(threemonths_ago, today)).order_by('request_time')
        context.update({
            'followed':followed,
            'I_unanswered_qBox':I_unanswered_qBox,
            'I_unanswered_addExc':I_unanswered_addExc,
        })
        return context




"""
大学生活情報登録・変更・削除
"""
class settingUnivLifeInfo(LoginRequiredMixin, generic.TemplateView):
    template_name = 'mypage/UserSetting/UnivLifeInfo.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        login_user = self.request.user
        try:
            myClub = club.objects.filter(user=login_user)
        except club.DoesNotExist:
            myClub = None
        try:
            openQ_and_myans = openQ_ans.objects.filter(user=login_user)
        except openQ_ans.DoesNotExist:
            openQ_and_myans = None
        context.update({
            'myclub':myClub,
            'openQ':openQ_and_myans,
        })
        return context

class addClub(LoginRequiredMixin, generic.CreateView):
    model = club
    form_class = club_form
    template_name = 'mypage/createOrUpdate.html'
    success_url = reverse_lazy('mypage:univlife_setting')
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(addClub, self).form_valid(form)
    def get_context_data(self, **kwargs):
        context = super(addClub, self).get_context_data(**kwargs)
        context["h2text"]="所属しているサークルや部活を追加"
        return context

class addopenQ(LoginRequiredMixin, generic.CreateView):
    model = openQ_ans
    form_class = openQ_ans_addform
    template_name = 'mypage/createOrUpdate.html'
    success_url = reverse_lazy('mypage:univlife_setting')
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(addopenQ, self).form_valid(form)
    def get_context_data(self, **kwargs):
        context = super(addopenQ, self).get_context_data(**kwargs)
        context["h2text"]="オープンクエスチョンを追加"
        return context
    def get_form_kwargs(self):
        kwargs = super(addopenQ, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

class updateClub(LoginRequiredMixin, generic.UpdateView):
    model = club
    form_class = club_form
    template_name = 'mypage/createOrUpdate.html'
    success_url = reverse_lazy('mypage:univlife_setting')
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(updateClub, self).form_valid(form)
    def get_object(self):
        obj=club.objects.get(id=self.kwargs['id'])
        if obj.user==self.request.user:
            return obj
        raise Http404
        return None
    def get_context_data(self, **kwargs):
        context = super(updateClub, self).get_context_data(**kwargs)
        context["h2text"]="所属しているサークルや部活を編集"
        return context

class updateOpenQ(LoginRequiredMixin, generic.UpdateView):
    model = openQ_ans
    form_class = openQ_ans_updateform
    template_name = 'mypage/createOrUpdate.html'
    success_url = reverse_lazy('mypage:univlife_setting')
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(updateOpenQ, self).form_valid(form)
    def get_object(self):
        obj=openQ_ans.objects.get(id=self.kwargs['id'])
        if obj.user==self.request.user:
            return obj
        raise Http404
        return None
    def get_context_data(self, **kwargs):
        context = super(updateOpenQ, self).get_context_data(**kwargs)
        context["h2text"]="オープンクエスチョンを編集"
        return context
    def get_form_kwargs(self):
        kwargs = super(updateOpenQ, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        kwargs['openq'] = openQ_ans.objects.get(id=self.kwargs['id']).openQ
        return kwargs

class deleteClub(LoginRequiredMixin, generic.DeleteView):
    model = club
    template_name = 'mypage/confirmDel.html'
    success_url = reverse_lazy('mypage:univlife_setting')
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(deleteClub, self).form_valid(form)
    def get_object(self):
        obj=club.objects.get(id=self.kwargs['id'])
        if obj.user==self.request.user:
            return obj
        raise Http404
        return None
    def get_context_data(self, **kwargs):
        context = super(deleteClub, self).get_context_data(**kwargs)
        context["h2text"]="所属しているサークルや部活を削除します"
        return context

class deleteOpenQ(LoginRequiredMixin, generic.DeleteView):
    model = openQ_ans
    template_name = 'mypage/confirmDel.html'
    success_url = reverse_lazy('mypage:univlife_setting')
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(deleteOpenQ, self).form_valid(form)
    def get_object(self):
        obj=club.objects.get(id=self.kwargs['id'])
        if obj.user==self.request.user:
            return obj
        raise Http404
        return None
    def get_context_data(self, **kwargs):
        context = super(deleteOpenQ, self).get_context_data(**kwargs)
        context["h2text"]="オープンクエスチョンを削除します"
        return context





"""
就活情報登録・変更・削除
"""
class setting_jobHuntingInfo(LoginRequiredMixin, generic.TemplateView):
    template_name='mypage/UserSetting/JobHuntingInfo.html'

    def get_context_data(self, **kwargs):
        context =super().get_context_data(**kwargs)
        login_user=self.request.user
        try:
            req = jobHunting_requestment.objects.get(user=login_user)
        except :
            req = None
        try:
            start = jobHunting_startTime.objects.get(user=login_user)
        except :
            start = None
        try:
            policy = jobHunting_policy.objects.get(user=login_user)
        except:
            policy = None
        try:
            internshipRec = internshipRecommendation.objects.filter(user=login_user)
        except internshipRecommendation.DoesNotExist:
            internshipRec = None
        try:
            prospectiveEmp = prospectiveEmployer.objects.filter(user=login_user)
        except prospectiveEmployer.DoesNotExist:
            prospectiveEmp = None
        
        context.update({
            'jobReqestment':req,
            'jobHunting_StartTime':start,
            'policy':policy,
            'internshipRec':internshipRec,
            'prospectiveEmployer':prospectiveEmp,
        })
        return context

class jobHunting_requestment_view(LoginRequiredMixin, generic.UpdateView):
    model = jobHunting_requestment
    template_name='mypage/createOrUpdate.html'
    form_class = jobHunting_requestment_form
    success_url = reverse_lazy('mypage:jobhunting_setting')
    def get_object(self):
        login_user=self.request.user
        try:
            req = jobHunting_requestment.objects.get(user=login_user)
        except:
            req = jobHunting_requestment()
            req.user = login_user
        return req
    def get_context_data(self, **kwargs):
        context = super(jobHunting_requestment_view, self).get_context_data(**kwargs)
        context['h2text']="就職希望を登録する"
        return context

class jobHunting_startTime_view(LoginRequiredMixin, generic.UpdateView):
    template_name='mypage/createOrUpdate.html'
    form_class = jobHunting_startTime_form
    model = jobHunting_startTime
    success_url = reverse_lazy('mypage:jobhunting_setting')
    def get_object(self):
        login_user=self.request.user
        try:
            start = jobHunting_startTime.objects.get(user=login_user)
        except:
            start  = jobHunting_startTime()
            start.user = login_user
        return start
    def get_context_data(self, **kwargs):
        context = super(jobHunting_startTime_view, self).get_context_data(**kwargs)
        context["h2text"]="就活開始時期を登録する"
        return context

class jobHuntingPolicy_view(LoginRequiredMixin, generic.UpdateView):
    template_name='mypage/createOrUpdate.html'
    form_class = jobHunting_policy_form
    model = jobHunting_policy
    success_url = reverse_lazy('mypage:jobhunting_setting')
    def get_object(self):

mypage/templates/mypage/UserSetting/JobHuntingInfo.html
{% extends "accounts/base.html" %}
{% block class %}
<style>
  .content{
    padding: 5vw;
    padding-top: 5vw;
  }
</style>
{% endblock %}
{% block content %}
<div class="content">
  <h3>就活希望</h3>
  <a href="{% url 'mypage:jobhunting_requestment' %}"><i class="fas fa-edit">edit</i></a>
  <table class="table">
    <tr>
      <td>
        <p>希望業界：</p>
        {{ jobReqestment.industry }}
      </td>
    </tr>
    <tr>
      <td>
        <p>希望職種：</p>
        {{ jobReqestment.occupation }}
      </td>
    </tr>
    <tr>
      <td>
        <p>希望勤務地：</p>
        {{ jobReqestment.workplace }}
      </td>
    </tr>
  </table>


  <div style="display: inline;">
    <h3>就活の軸</h3>
    <a href="{% url 'mypage:jobhunting_policy' %}"><i class="fas fa-edit">edit</i></a>
  </div>

  <table class="table">
    <tr>
      <td>
        <p>就活の中で大切にしたこと：</p>
        {{ policy.policy|linebreaksbr }}
      </td>
    </tr>
  </table>


  <div style="display: inline;">
    <h3>就活ログ</h3>
    <a href="{% url 'mypage:jobhunting_startTime' %}"><i class="fas fa-edit">edit</i></a>
  </div>

  <table class="table">
    <tr>
      <td>
        <p>就活を始めた時期：</p>
        {{ jobHunting_StartTime.season }}
      </td>
    </tr>
  </table>


  <h3>おすすめのインターンシップ</h3>
  <a href="{% url 'mypage:jobhunting_internRec_create' %}"><i class="fas fa-plus">add</i></a>
  {% for field in internshipRec %}
  <table class="table">
    <tr>
      <td>
        <p>業界：</p>
        {{ field.industry }}
      </td>
    </tr>
    <tr>
      <td>
        <p>職種：</p>
        {{ field.occupation }}
      </td>
    </tr>
    <tr>
      <td>
        <p>社名：</p>
        {{ field.company_name }}
      </td>
    </tr>
    <tr>
      <td>
        <p>時期：</p>
        {{ field.season }}
      </td>
    </tr>
    <tr>
      <td>
        <p>期間：</p>
        {{ field.period }}
      </td>
    </tr>
    <tr>
      <td>
        <p>内容：</p>
        {{ field.overView }}
      </td>
    </tr>
    <tr>
      <td>
        <p>感想：</p>
        {{ field.implessions }}
      </td>
    </tr>
    <tr>
      <td>
        <p>最終更新日：</p>
        {{ field.post_date }}
      </td>
    </tr>
    <tr>
      <td>
          <a href="{% url 'mypage:jobhunting_internRec_update' id=field.id %}"><i class="fas fa-edit">edit</i></a>
      </td>
      <td>
          <a href="{% url 'mypage:jobhunting_internRec_delete' id=field.id %}"><i class="fas fa-trash">delete</i></a>
      </td>
    </tr>
  </table>
  {% endfor %}


  <h3>内定した会社</h3>
  <a href="{% url 'mypage:jobhunting_prospectiveEmployer_create' %}"><i class="fas fa-plus">add</i></a>
  {% for field in prospectiveEmployer %}
  <table class="table">
    <tr>
      <td>
        <p>業界：</p>
        {{ field.industry }}
      </td>
    </tr>
    <tr>
      <td>
        <p>職種：</p>
        {{ field.occupation }}
      </td>
    </tr>
    <tr>
      <td>
        <p>社名：</p>
        {{ field.company_name }}
      </td>
    </tr>
    <tr>
      <td>
        <a href="{% url 'mypage:jobhunting_prospectiveEmployer_update' id=field.id %}"><i class="fas fa-edit">edit</i></a>
      </td>
      <td>
        <a href="{% url 'mypage:jobhunting_prospectiveEmployer_delete' id=field.id %}"><i class="fas fa-trash">delete</i></a>
      </td>
    </tr>
  </table>
  {% endfor %}

</div>
{% endblock %}

mypage/templates/mypage/UserSetting/UnivLifeInfo.html
{% extends "accounts/base.html" %}
{% load utility %}
{% load static %}

{% block class %}
<link href="{% static 'css/table.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="content">
  <h3>所属しているサークルや部活</h3>
  <a href="{% url 'mypage:univlife_club_add' %}"><i class="fas fa-plus">add</i></a>
  {% for field in myclub %}
  <table class="table">
    <tr>
      <td>
        <p>名称：</p>
        {{ field.club_name }}
      </td>
    </tr>
    <tr>
      <td>
        <p>最終更新日：</p>
        {{ field.post_date }}
      </td>
    </tr>
    <tr>
      <td>
          <a href="{% url 'mypage:univlife_club_update' id=field.pk %}"><i class="fas fa-edit">edit</i></a>
      </td>
      <td>
          <a href="{% url 'mypage:univlife_club_delete' id=field.pk %}"><i class="fas fa-trash">delete</i></a>
      </td>
    </tr>
  </table>
  {% endfor %}

  <h3>オープンクエスチョン</h3>
  {% if openQ.count|isTooManyOpenQs %}
  <a href="{% url 'mypage:univlife_openQ_add' %}"><i class="fas fa-plus">add</i></a>
  {% endif %}

  {% for field in openQ %}
  <table class="table">
    <tr>
      <td>
        <p>質問：</p>
        {{ field.openQ }}
      </td>
    </tr>
    <tr>
      <td>
        <p>回答：</p>
        {{ field.ans }}
      </td>
    </tr>
    <tr>
          <td>
            <p>最終更新日：</p>
            {{ field.post_date }}
          </td>
    </tr>
    <tr>
      <td>
          <a href="{% url 'mypage:univlife_openQ_update' id=field.pk %}"><i class="fas fa-edit">edit</i></a>
      </td>
      <td>
          <a href="{% url 'mypage:univlife_openQ_delete' id=field.pk %}"><i class="fas fa-trash">delete</i></a>
      </td>
    </tr>
  </table>
  {% endfor %}
</div>
{% endblock %}