ShakeHands/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('questionBoxes/', include('questionBoxes.urls', namespace = 'questionBoxes')),
    path('address_exchange/', include('addexchange.urls', namespace = 'addexchange')),
    path('',include('mypage.urls', namespace ='mypage')),
]

# 以下、media用の定義
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

addexchange/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name ='addexchange'
urlpatterns=[
    path('request/<uuid:id>/',views.addExc.as_view(),name='request'),
    path('list/',views.addExchange_list.as_view(),name='list'),
    path('detail/<uuid:id>/',views.detail.as_view(),name='detail'),
    path('approve/<uuid:id>/',views.confirm.as_view(),name='confirm'),
]

mypage/urls.py
from . import views
from django.urls import path, include
#from django.contrib.auth import views as auth_views

app_name = 'mypage'

urlpatterns = [
    path('', views.top.as_view(), name='top'),

    #学生生活情報の編集ページ
    path('setting/univlife/',views.settingUnivLifeInfo.as_view(), name='univlife_setting'),
    path('setting/univlife/club/add/',views.addClub.as_view(), name='univlife_club_add'),
    path('setting/univlife/club/update/<int:id>',views.updateClub.as_view(), name='univlife_club_update'),
    path('setting/univlife/club/delete/<int:id>',views.deleteClub.as_view(), name='univlife_club_delete'),
    path('setting/univlife/openQ/add/',views.addopenQ.as_view(), name='univlife_openQ_add'),
    path('setting/univlife/openQ/update/<int:id>',views.updateOpenQ.as_view(), name='univlife_openQ_update'),
    path('setting/univlife/openQ/delete/<int:id>',views.deleteOpenQ.as_view(), name='univlife_openQ_delete'),

    #就活情報の編集ページ
    path('setting/jobhunting/',views.setting_jobHuntingInfo.as_view(), name='jobhunting_setting'),
    path('setting/jobhunting/policy',views.jobHuntingPolicy_view.as_view(), name='jobhunting_policy'),
    path('setting/jobhunting/startTime',views.jobHunting_startTime_view.as_view(), name='jobhunting_startTime'),
    path('setting/jobhunting/requestment',views.jobHunting_requestment_view.as_view(), name='jobhunting_requestment'),
    path('setting/jobhunting/internship/create',views.internshipRec_create.as_view(), name='jobhunting_internRec_create'),
    path('setting/jobhunting/internship/update/<uuid:id>',views.internshipRec_update.as_view(), name='jobhunting_internRec_update'),
    path('setting/jobhunting/internship/delete/<uuid:id>',views.internshipRec_delete.as_view(), name='jobhunting_internRec_delete'),
    path('setting/jobhunting/prospectiveEmployer/create',views.prospectiveEmployer_create.as_view(), name='jobhunting_prospectiveEmployer_create'),
    path('setting/jobhunting/prospectiveEmployer/update/<uuid:id>',views.prospectiveEmployer_update.as_view(), name='jobhunting_prospectiveEmployer_update'),
    path('setting/jobhunting/prospectiveEmployer/delete/<uuid:id>',views.prospectiveEmployer_delete.as_view(), name='jobhunting_prospectiveEmployer_delete'),

    #プロフィールページ
    path('profile/<uuid:id>',views.profilePage.as_view(),name='profile'),
    path('search/all',views.allUser_list.as_view(),name='alluser_list'),

    #フォロー一覧
    path('friends/', views.follower_list.as_view(), name='follower_list'),
    path('search/',views.Search.as_view(),name='searchuser'),
]

questionBoxes/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'questionBoxes'

urlpatterns = [
    #path('', views.Top.as_view(), name='login'),
    path('create/<uuid:id>', views.CreateQuestionView.as_view(), name='create'),
    path('answer/<uuid:id>', views.AnswerView.as_view(), name='answer'),
    path('list/',views.list.as_view(),name='list'),
    path('detail/<uuid:id>', views.QBoxView.as_view(),name='detail'),
    path('search_questionbox/',views.Search_question.as_view(),name='searchquestion')
]

accounts/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.base_user import BaseUserManager
from django.core.validators import MaxValueValidator, MinValueValidator

import uuid
from json import JSONEncoder
from uuid import UUID

JSONEncoder_olddefault = JSONEncoder.default

def JSONEncoder_newdefault(self, o):
    if isinstance(o, UUID): return str(o)
    return JSONEncoder_olddefault(self, o)

JSONEncoder.default = JSONEncoder_newdefault


class UserManager(BaseUserManager):
    """ユーザーマネージャー."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """メールアドレスでの登録を必須にする"""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """is_staff(管理サイトにログインできるか)と、is_superuer(全ての権限)をFalseに"""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """スーパーユーザーは、is_staffとis_superuserをTrueに"""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """カスタムユーザーモデル."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=False)
    last_name = models.CharField(_('last name'), max_length=150, blank=False)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """Return the first_name plus the last_name, with a space in
        between."""
        full_name = '%s %s' % (self.last_name, self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)


    @property
    def username(self):
        """username属性のゲッター

        他アプリケーションが、username属性にアクセスした場合に備えて定義
        メールアドレスを返す
        """
        return self.email



COURSE_CHOICES=(
    ('1','英語英文学科'),
    ('2','国際関係学科'),
    ('3','多文化・国際協力学科'),
    ('4','数学科'),
    ('5','情報科学科'),
    ('6','総合政策学科'),
)
class UserSetting(models.Model):
    #仮登録だったユーザを本登録するためのModel
    #姓名とemailはCreateUserの方で登録してある。
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    display_name = models.CharField("表示名",max_length=50,blank=True)
    icon_pic = models.ImageField( "アイコン画像" , upload_to='images/', blank=True, null=True)
    graduation_year = models.IntegerField("卒業年(西暦下2桁)",blank=False,validators=[MinValueValidator(0),MaxValueValidator(99)])
    course = models.CharField("所属学科",max_length=2,choices=COURSE_CHOICES,blank=False)

class userComment(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    comment = models.TextField("自己紹介", max_length=200, null=True)

mypage/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import (
    club, openQ, openQ_ans,
    jobHunting_requestment, jobHunting_startTime,
    internshipRecommendation, prospectiveEmployer,
    myfriend, jobHunting_policy
)

User=get_user_model()

class club_form(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
    class Meta:
        model = club
        fields = (
            'club_name',
        )

class openQ_ans_addform(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['openQ'].queryset = self.get_q()
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
    class Meta:
        model = openQ_ans
        fields= (
            'openQ',
            'ans',
        )
    def get_q(self):
        login_user = self.user
        if openQ.objects.count() <= openQ_ans.objects.filter(user = login_user).count():
            return openQ.objects.none()
        return openQ.objects.all().exclude(openq_ans__user=login_user)
        

class openQ_ans_updateform(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        self.openq = kwargs.pop('openq')
        super().__init__(*args, **kwargs)
        self.fields['openQ'].queryset = self.get_q()
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
    class Meta:
        model = openQ_ans
        fields= (
            'openQ',
            'ans',
        )
    def get_q(self):
        login_user = self.user
        if openQ.objects.count() <= openQ_ans.objects.filter(user = login_user).count():
            return openQ.objects.note()
        selected=openQ.objects.all().filter(id=self.openq.id)
        choices=openQ.objects.all().exclude(openq_ans__user=login_user)
        return (selected|choices)


class jobHunting_requestment_form(forms.ModelForm):
    #就職の希望を書くやつ
    class Meta:
        model = jobHunting_requestment
        fields = (
            'industry',
            'occupation',
            'workplace',
        )
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['industry'].required = False
        self.fields['occupation'].required = False
        self.fields['workplace'].required = False
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
    

class jobHunting_startTime_form(forms.ModelForm):
    #就職始めた時期を書くところ
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
    class Meta:
        model = jobHunting_startTime
        fields = (
            'season',
        )

class internshipRec_form(forms.ModelForm):
    #就職の希望を書くやつ
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['implessions'].required = False
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
    class Meta:
        model = internshipRecommendation
        fields = (
            'industry',
            'occupation',
            'company_name',
            'season',
            'period',
            'overView',
            'implessions',
        )

class prospectiveEmployer_form(forms.ModelForm):
    #就職の希望を書くやつ
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
    class Meta:
        model = prospectiveEmployer
        fields = (
            'industry',
            'occupation',
            'company_name',
        )

class myfriend_form(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(myfriend_form, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
    class Meta:
        model = myfriend
        fields = (
            'user',
            'friend',
        )
    def save(self):
        friend = super(myfriend_form,self).save()
        return friend

class jobHunting_policy_form(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(jobHunting_policy_form, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
    class Meta:
        model = jobHunting_policy
        fields = ('policy',)

mypage/templates/mypage/comfirmDel.html
{% extends "mypage/base.html" %}
{% block content %}
<h2>{{h2text}}</h2>
<form action="" method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary btn-lg">削除する</button>
</form>
{% endblock %}

mypage/templates/mypage/confirmDel.html
{% extends "accounts/base.html" %}
{% block content %}
<h2>{{h2text}}</h2>
<form action="" method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary btn-lg">削除する</button>
</form>
{% endblock %}

mypage/templates/mypage/mypage.html
{% extends "mypage/base.html" %}
{% block content %}
<p>
    Mypage<br>
</p>
{% endblock %}

mypage/templates/mypage/profile.html
{% extends "accounts/base.html" %}
{% load static %}
{% load utility %}
{% block class %}
<!-- cssを追加できる -->
<link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<!--青色の所全体-->
<div class ="profile_head row d-flex align-items-center">
   <!--アイコン画面　青色の左部分col-3-->
        <img src="{{user_detail.user.id|get_iconpic_url}}" class="col-3 img-fluid">


    <!--アイコン画面　青色の右部分col-9-->
    <div class ="col-9">

        <!--名前とか年度卒とかの行-->
        <div class="row d-flex align-items-center container-fluid">
            <div class="col-9">
                <h4>{{ display_name }}</h4>
                
                <a>{{ user_detail.graduation_year }}年度卒</a><br>
                <a>{{ user_detail.get_course_display }}</a>
            
            </div>
            
               
        </div>

        <!--フォローボタンと空白の行-->
        <div class="row container-fluid ">
            <!--空白col-4-->
            <div class="col-4"></div>
            <!--フォローボタンcol-8-->
            <div class="col-8 ">
            {% if follow_state != 5%}
                <form action="" method="POST">
            {% csrf_token %}
                    <input type="hidden" name="followstate_ChangeParam" value="{{follow_state}}">
                    <button type="submit" class="btn btn-outline-secondary btn-sm align-self-end">{{followButton_txt}}</button> 
                 </form>     
            {% endif %} 
            </div>
        </div>           
    
        <div class="userComment">
        <a>{{ userComment.comment }}</a>    
        </div>
    </div> 
</div>

    <ul class="nav nav-tabs">
        <li class="nav-item" >
            <a href="#tab1" class="nav-link navbar-default active" data-toggle="tab" style="font-size: 10px;width: 90px;">大学生活</a>
        </li>
        <li class="nav-item">
            <a href="#tab2" class="nav-link navbar-default" data-toggle="tab" style="font-size: 10px;width: 90px;">就職活動</a>
        </li>
        {% if follow_state == 1 %}
        <li class="nav-item">
            <a href="#tab3" class="nav-link navbar-default" data-toggle="tab" style="font-size: 10px;width: 150px;">相互フォロワー機能</a>
        </li>
        {% endif %}
    </ul>

        <!--タブの中身-->
        <div class="tab-content">
            <div id="tab1" class="tab-pane active content_into_tab">
                <!--Tab1の内容-->
                <div class ="sep_data">
                    <h4>所属しているサークルや部活</h4>
                    {% for field in club %}
                    <table class="table sep_data">
                        <tr>
                            <td>
                                <p>名称：</p>
                                {{ field.club_name }}
                            </td>
                        </tr>
                    </table>
                    {% endfor %}
                </div>
                <div class ="sep_data">
                        <h4>オープンクエスチョン</h4>
                        {% for field in openQ %}
                        <table class="table sep_data">
                            <tr>
                                <td>
                                    <p>質問：</p>
                                    {{ field.openQ }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                        
                                        <div id="accordion">
                                          <div class="card" style="background-color: #ffffff;">
                                            <div class="card-header" id="heading-{{ forloop.counter }}">
                                              <h5 class="mb-0">
                                                <button class="btn btn-link" data-toggle="collapse" data-target="#collapse-{{ forloop.counter }}" aria-expanded="false" aria-controls="collapse-{{ forloop.counter }}">
                                                  回答をみる
                                                </button>
                                              </h5>
                                            </div>
                                        
                                            <div id="collapse-{{ forloop.counter }}" class="collapse" aria-labelledby="heading-{{ forloop.counter }}" data-parent="#accordion">
                                              <div class="card-body">
                                                  {{ field.ans|linebreaksbr }}
                                            
                                              </div>
                                            </div>
                                          </div>
                                        </div>
                                    
                                    
                                </td>
                            </tr>
                        </table>
                        {% endfor %}
                </div>               
            </div>
            <div id="tab2" class="tab-pane content_into_tab">
                <!--Tab２の内容-->
                <div class ="sep_data">
                    <h4>就活希望</h4>
                    <table class="table">
                        <tr>
                            <td>
                                <p>希望業界：</p>
                                {{ jobReqestment.industry }}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <p>希望職種：</p>
                                {{ jobReqestment.occupation }}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <p>希望勤務地：</p>
                                {{ jobReqestment.workplace }}
                            </td>
                        </tr>
                    </table>
                </div>
                

                <div class ="sep_data">
                    <h4>就活ログ</h4>
                    <table class="table">
                        <tr>
                            <td>
                                <p>就活の軸：</p>
                                {{ policy.policy|linebreaksbr }}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <p>就活を始めた時期：</p>
                                {{ jobHunting_startTime.season|linebreaksbr }}
                            </td>
                        </tr>

                    </table>
                </div>

    

                <div class ="sep_data">
                    <h4>おすすめのインターンシップ</h4>
                    {% for field in internship_rec %}
                        <table class="table">
                            <tr>
                                <td>
                                    <p>業界：</p>
                                    {{ field.industry }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <p>職種：</p>
                                    {{ field.occupation }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <p>社名：</p>
                                    {{ field.company_name }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <p>時期：</p>
                                    {{ field.season }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <p>期間：</p>
                                    {{ field.period }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <p>内容：</p>
                                    {{ field.overView|linebreaksbr }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <p>感想：</p>
                                    {{ field.implessions|linebreaksbr }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <p>最終更新日：</p>
                                    {{ field.post_date }}
                                </td>
                            </tr>
                        </table>
                    {% endfor %}
                    </div>
                </div>
                

            <div id="tab3" class="tab-pane content_into_tab">
                <!--Tab３の内容-->
                <div class="container-fluid">
                    <div class="row justify-content-start">
                        <div class="col-9">   
                            <a href="{% url 'questionBoxes:create' id=display_user.pk %}"class="btn btn-sm btn-info" role="button">質問する</a><br>
                        </div>
                    </div>
                    <div class="row justify-content-start">
                        <div class="col-auto">
                            <div class="alert alert-warning  mt-3 mb-5" role="alert">
                            質問内容は、全てのユーザーに公開されるため、 回答者と質問者の本名を文章中に記載しないよう御願い致します。
                            </div> 
                        </div>
                    </div>
                    <div class="row justify-content-start">
                        <div class="col-9">   
                            <a href="{% url 'addexchange:request' id=display_user.pk %}"class="btn btn-sm btn-info" role="button">アドレス交換申請する</a><br>
                        </div>
                        
                    </div>
                </div>
              
            </div>

        </div>   
    </div>
{% endblock %}

mypage/templates/mypage/search.html
{% extends 'accounts/base.html' %}
{% load utility %}  
{% load custom_filters %}
{% load static %}
{% block class %}
<link rel="stylesheet" href="{% static '/css/search_user.css' %}">
{% endblock %}
{% block content %}
    <form method="get" action="" name="filter_form">
        <legend>ユーザー検索</legend>
        <div>
        {% comment %} <input type="search" autocomplete="on"  id="filter_name" > {% endcomment %}
        <span>学科</span>
        <select name="course">
        <option value ="">--------</option>
        <option value ="1">英語英文学科</option>
        <option value="2">国際関係学科</option>
        <option value="3">多文化・国際協力学科</option>
        <option value="4">数学科</option>
        <option value="5">情報科学科</option>
        <option value="6">総合政策学科</option>
        </select>
        <button id="filter">絞り込み</button>
        
        </div>
           
        <div id="main">
        <br>
        <br>
        <legend>結果</legend>
        <table>           
            {% for user in object_list %}
            <div class="linklink">
                <p class="card-text"> 
                    <div class ="profile_head row d-flex align-items-center">                
                        <img src="{{user.user.id|get_iconpic_url}}" class="col-3 img-fluid">
                        <div class ="col-9">
                            <div class="row d-flex align-items-center container-fluid">
                                卒業年度:{{ user.graduation_year  }}
                                <br>
                                学科:{{ user.get_course_display }}      
                                <br>
                                名前:{{ user.display_name }}
                            </div>
                        </div>

                    </div>
                </p>
                <a class="Link" href="{% url 'mypage:profile' id=user.user.pk %}"></a>
            </div>
            {% endfor %}
        </table>
    </div>
    <!-- 前へ の部分 -->
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">前へ</a>
    {% endif %}

    <!-- 1/3 の部分 -->
   {{ page_obj.number }}/{{ page_obj.paginator.num_pages }}

    <!-- 次へ の部分 -->
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">次へ</a>
    {% endif %}
    {% endblock %}

mypage/templates/mypage/top.html
{% extends 'accounts/base.html' %}
{% load utility %}
{% load static %}

{% block class %}
<link href="{% static 'css/top.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

<div class="all">
    <h2>News</h2>
    <div class ="news">
        <h3>新着フォロワー</h3>
        <div class="overflow-auto area-border">
            {% if followed.count is 0 %}
            <p>・新着情報はまだありません</p>
            {% endif %}
            {% for user in followed %}
            {% with id=user.user %}
            
            <div class="overflow-hidden row d-flex align-items-center container-fluid linklink">
                <a href="{% url 'mypage:profile' id=id %}"></a>
                <div class = "col-3">
                    {% if id|get_iconpic_url %}
                    <img src="{{ id|get_iconpic_url }}" class="img-fluid">
                    {% endif %}
                </div>
                <div class ="col-9">    
                        <div class=profile_txt>
                            <h5>{{ id|get_displayname }}</h5>
                            <p>{{ id|get_course }}学科 {{ id|get_graduationyear }}</p>
                        </div>
                        
                </div>
                <a class="Link" href="{% url 'mypage:profile' id=id %}"></a>
            </div>
            {% endwith %}
            {% endfor %}
        </div>     
    </div>
    <div class = "news">
        <h3>新着質問</h3>
        <div class="overflow-auto area-border">
            {% if I_unanswered_qBox.count is 0 %}
            <p>・新着情報はまだありません</p>
            {% endif %}
            {% for qbox in I_unanswered_qBox %}
                <div class="overflow-hidden row d-flex align-items-center container-fluid">
                    <a href="{% url 'questionBoxes:answer' id=qbox.pk %}"></a>
                    <div class="col-12">
                    <div class="linklink">
                
                        <div>  
                            <p>{{ qbox.questionner.id|get_course }}学科 {{ qbox.questionner.id|get_graduationyear }} {{ qbox.questionner.id|get_displayname }}</p>
                        </div>
                
                        <div>
                            <p>質問日時：{{ qbox.created_at|date:"Y-m-d" }}</p>
                        </div>
                        <div>
                            <p>タイトル：{{ qbox.title}}</p>
                        </div>
                        <a class="Link"  href="{% url 'questionBoxes:answer' id=qbox.id %}"></a>
                    </div>
                    </div>

            
                </div>
            {% endfor %}
        </div>
    </div>
    <div class ="news">
        <h3>新着アドレス交換申請</h3>  
        <div class="overflow-auto area-border">
            {% if I_unanswered_addExc.count is 0 %}
            <p>・新着情報はまだありません</p>
            {% endif %}
            {% for addexc in I_unanswered_addExc %}
            <div class="overflow-hidden row d-flex align-items-center container-fluid">
                <a href="{% url 'addexchange:detail' id=addexc.pk %}"></a>
                
                    <div class="col-12">
                    
                        <div class ="linklink">
                            {{ addexc.questioner.id|get_course }}学科  {{ addexc.questioner.id|get_graduationyear }} {{ addexc.questioner.id|get_displayname }}
                            <br>
                            申請日時: {{ addexc.request_time|date:"Y-m-d" }}
                            <a class="Link" href="{% url 'addexchange:confirm' id=addexc.pk %}"></a>
                        </div>
                        
                    </div>
                
                   
            </div>
            {% endfor %}
        </div>  
    </div>
</div>
{% endblock %}

mypage/templates/mypage/userlist.html
{% extends 'accounts/base.html' %}
{% load utility %}

{% block content %}
    {% for user in users %}
        <div>
            {% if user.icon_pic %}
            <img src="{{user.icon_pic.url}}" class="col-3">
            {% endif %}
            <div class ="col-9">
                <div class=profile_txt>
                    <a href="{% url 'mypage:profile' id=user.user.pk %}">{{ user.user.id|get_displayname }}</a>
                    <a>{{ user.graduation_year }}年度卒業</a><br>
                    <a>{{ user.get_course_display }}学科</a><br>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}